name: minikiosk
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  kiosk_mode: ^0.5.0+2
  global_settings_list: ^0.1.1
  webview_flutter: ^4.4.4
  webview_flutter_android: ^3.14.0
  webview_flutter_wkwebview: ^3.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
